import type { UiDictionary } from "@/i18n/types";

export const en = {
  locale: "en",
  nav: { projects: "Projects", about: "About", stack: "Stack", github: "GitHub", contact: "Contact", home: "Home", primary: "Main navigation", mobile: "Mobile navigation", openMenu: "Open menu", closeMenu: "Close menu", languageSwitch: "Switch to Russian" },
  buttons: { contact: "Contact", projects: "View projects", details: "Details", caseStudy: "Case study", live: "Live", code: "Code", back: "Back", backToProjects: "Back to projects", profile: "Open GitHub profile", retry: "Try again", returnHome: "Home", readme: "README" },
  home: {
    available: "Open to work", heroTitle: "Full-Stack Developer",
    heroDescription: "I create web products end to end — from interface to database. My projects include an online exam platform for an educational center, a day-planning system, and a desktop utility for transferring files over a local network. I am developing toward backend work — Supabase, PostgreSQL, C#/.NET.",
    heroTech: "React · Next.js · TypeScript · Firebase", featuredTitle: "Selected projects", featuredDescription: "Main projects — production products and complex systems.", otherTitle: "Other projects", otherDescription: "Side projects and experiments.", aboutTitle: "About me",
    aboutIntro: "Full-stack developer from Osh, Kyrgyzstan. I build web products end to end: interfaces with React and Next.js, data with Firebase and Supabase, and deployment on Vercel. I wrote all projects in this portfolio myself.",
    aboutDetails: "The latest major project is an online exam platform for PROlab Academy: separate flows for teachers and students, anti-cheating protection, and database-level access control through Row Level Security. I also built a day-planning system with habits and goals, and a C# desktop utility for transferring files over a local network.",
    experienceTitle: "Experience", experienceDate: "2026 — present", experienceRole: "Frontend development", experienceType: "Internship", experienceDescription: "Frontend tasks in real projects — my first work experience outside personal projects.", stackTitle: "Tech stack", principlesTitle: "How I work", githubTitle: "GitHub", pinned: "Pinned repositories", languages: "Languages", languageChart: "Language distribution across repositories", recent: "Recent activity", githubError: "GitHub data could not be loaded. Try refreshing the page later.", contactTitle: "Open to internships and projects", contactDescription: "Need a frontend or full-stack task, have a question about the projects, or an internship proposal? Write on Telegram or by email.", caseLink: "PROlab Academy — case study",
  },
  pages: { aboutTitle: "About me", aboutDescription: "Full-stack developer from Osh, Kyrgyzstan: an online exam platform, a day-planning system, and desktop utilities. React, Next.js, TypeScript, Firebase, Supabase.", stack: "Stack", projectsTitle: "All projects", projectsDescription: "Production products, complex systems, and side projects.", contactTitle: "Contacts", contactDescription: "Contacts: Telegram, email, and GitHub. Open to internships and new projects.", profileTitle: "Profile", profileDescription: "GitHub data — repositories and profile activity.", profileError: "GitHub data could not be loaded. Try again later.", repositories: "Repositories", openGithub: "Open on GitHub" },
  project: { overview: "Overview", problem: "Problem", scope: "Role and scope", features: "Key features", architecture: "Architecture", decisions: "Technical decisions", limitations: "Limitations", screenshots: "Screenshots" },
  states: { loading: "Loading…", notFound: "Page not found", notFoundDescription: "This page may not exist or may have been moved.", errorTitle: "Something went wrong", errorDescription: "An unexpected error occurred. We are already working on it.", noResults: "Nothing found.", noReadme: "This repository has no README.", readmeError: "README could not be loaded.", sort: "Sort", all: "All", sortStars: "by stars", sortUpdated: "by update date", sortName: "by name" },
  aria: { themeLight: "Switch to dark theme", themeDark: "Switch to light theme", mainNav: "Main navigation", mobileNav: "Mobile navigation", languageChart: "Language distribution across repositories", sortRepositories: "Sort repositories", showReadme: (name) => `Show README for repository ${name}`, readmeOf: (name) => name ? `README for repository ${name}` : "Repository README", avatarOf: (name) => `Avatar of ${name}` },
  principles: [
    { title: "Think in systems", description: "I understand the whole chain: from interface through API and backend to the database. Not isolated pieces, but a complete architecture." },
    { title: "Build for production", description: "I consider security, validation, error handling, performance, testing, and deployment — not only whether it works on my machine." },
    { title: "Solve problems", description: "I can investigate complex bugs and understand their cause instead of simply copying solutions from Stack Overflow." },
    { title: "Keep learning", description: "I keep expanding my stack: from frontend (Next.js, TypeScript, Tailwind) toward the full cycle — Supabase, PostgreSQL, Python, Django, and C#." },
  ],
  techGroups: ["Core stack", "Used in real projects", "Learning"],
} satisfies UiDictionary;
