import type { UiDictionary } from "@/i18n/types";

export const en = {
  locale: "en",
  nav: { projects: "Projects", about: "About", stack: "Stack", github: "GitHub", contact: "Contact", home: "Home", primary: "Main navigation", mobile: "Mobile navigation", openMenu: "Open menu", closeMenu: "Close menu", languageSwitch: "Switch to Russian" },
  buttons: { contact: "Contact", projects: "View projects", details: "Details", caseStudy: "Case study", live: "Live", code: "Code", back: "Back", backToProjects: "Back to projects", profile: "Open GitHub profile", retry: "Try again", returnHome: "Home", readme: "README", close: "Close" },
  home: {
    available: "Open to work", heroTitle: "Full-Stack Developer",
    heroDescription: "I create web products end to end — from interface to database. I work with frontend and backend parts of projects, databases, and integrations. My projects include an online exam platform for an educational center, a day-planning system, and a desktop utility for transferring files over a local network.",
    heroTech: "React · Next.js · TypeScript · Firebase", featuredTitle: "Selected projects", featuredDescription: "Projects pinned on GitHub.", selectedWorkEmpty: "Pinned projects are currently unavailable.", otherTitle: "Other projects", otherDescription: "Side projects and experiments.", aboutTitle: "Full-Stack Developer from Kyrgyzstan.",
    aboutIntro: "I develop web products with React and Next.js, and work with backend systems and databases. I use TypeScript, Firebase, Supabase, PostgreSQL, and other technologies depending on the project. This portfolio brings together projects I developed independently.",
    aboutDetails: "",
    experienceTitle: "Experience", experienceDate: "2026 — present", experienceRole: "Frontend development", experienceType: "Internship", experienceDescription: "Frontend tasks in real projects — my first work experience outside personal projects.", stackTitle: "Tech stack", principlesTitle: "How I work", githubTitle: "GitHub", pinned: "Pinned repositories", languages: "Languages", languageChart: "Language distribution across repositories", recent: "Recent activity", githubError: "GitHub data could not be loaded. Try refreshing the page later.", contactTitle: "Contact", contactDescription: "I develop web applications and continue growing in the full-stack direction. All main projects and source code are available in this portfolio.", roleLabel: "Solo Developer", architectureNodes: { frontend: "Frontend", api: "API", backend: "Backend", database: "Database" }, relativeJustNow: "just now",
  },
  pages: { aboutTitle: "About me", aboutDescription: "Full-Stack Developer from Kyrgyzstan: React, Next.js, TypeScript, Firebase, Supabase, and PostgreSQL.", stack: "Stack", projectsTitle: "All projects", projectsDescription: "Production products, complex systems, and side projects.", contactTitle: "Contact", contactDescription: "I develop web applications and continue growing in the full-stack direction. All main projects and source code are available in this portfolio.", profileTitle: "Profile", profileDescription: "GitHub data — repositories and profile activity.", profileError: "GitHub data could not be loaded. Try again later.", repositories: "Repositories", openGithub: "Open on GitHub", stats: ["repositories", "followers", "following"] },
  project: { overview: "Overview", problem: "Problem", scope: "Role and scope", features: "Key features", architecture: "Architecture", decisions: "Technical decisions", limitations: "Limitations" },
  states: { loading: "Loading…", notFound: "Page not found", notFoundDescription: "This page may not exist or may have been moved.", errorTitle: "Something went wrong", errorDescription: "An unexpected error occurred. We are already working on it.", noResults: "Nothing found.", noReadme: "This repository has no README.", readmeError: "README could not be loaded.", sort: "Sort", all: "All", sortStars: "by stars", sortUpdated: "by update date", sortName: "by name" },
  aria: { themeLight: "Switch to dark theme", themeDark: "Switch to light theme", mainNav: "Main navigation", mobileNav: "Mobile navigation", languageChart: "Language distribution across repositories", sortRepositories: "Sort repositories", showReadme: (name) => `Show README for repository ${name}`, readmeOf: (name) => name ? `README for repository ${name}` : "Repository README", avatarOf: (name) => `Avatar of ${name}` },
  principles: [
    { title: "Think in systems", description: "I understand the whole chain: from interface through API and backend to the database. Not isolated pieces, but a complete architecture." },
    { title: "Build for production", description: "I consider security, validation, error handling, performance, testing, and deployment — not only whether it works on my machine." },
    { title: "Solve problems", description: "I can investigate complex bugs and understand their cause instead of simply copying solutions from Stack Overflow." },
    { title: "Keep learning", description: "I keep expanding my full-stack practice: working with frontend, backend parts of projects, databases, and integrations — Next.js, Supabase, PostgreSQL, Python, Django, and C#." },
  ],
  techGroups: ["Core stack", "Work with", "Tools / infrastructure"],
} satisfies UiDictionary;
