import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { getGithubData } from "@/lib/github";
import RepoExplorer from "@/components/profile/RepoExplorer";
import { getDictionary } from "@/i18n";
import { isLocale, type Locale } from "@/i18n/config";
import { alternatesFor } from "@/i18n/metadata";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale: raw } = await params; const locale: Locale = isLocale(raw) ? raw : "ru"; const d = getDictionary(locale); return { title: d.pages.profileTitle, description: d.pages.profileDescription, alternates: alternatesFor("/profile", locale) }; }

export default async function ProfilePage({ params }: { params: Promise<{ locale: string }> }) { const { locale: raw } = await params; const locale: Locale = isLocale(raw) ? raw : "ru"; const d = getDictionary(locale); const { user, repos } = await getGithubData(); if (!user) return <div className="max-w-5xl mx-auto px-6 pb-24 font-sans"><h1 className="font-sans font-bold text-ink text-4xl md:text-5xl">{d.pages.profileTitle}</h1><p className="mt-6 text-muted">{d.pages.profileError}</p></div>; const stats = [{ value: user.public_repos, label: d.pages.stats[0] }, { value: user.followers, label: d.pages.stats[1] }, { value: user.following, label: d.pages.stats[2] }]; return <div className="max-w-5xl mx-auto px-4 md:px-6 pt-16 pb-24 font-sans"><h1 className="font-sans font-bold text-ink text-4xl md:text-5xl">{d.pages.profileTitle}</h1><header className="mt-8 flex flex-col sm:flex-row gap-8 sm:items-start">{user.avatar_url && <Image src={user.avatar_url} alt={d.aria.avatarOf(user.name ?? user.login)} width={120} height={120} className="rounded-none bg-line shrink-0" />}<div><div className="flex items-baseline gap-x-3 gap-y-1 flex-wrap"><h2 className="font-sans font-bold text-ink text-4xl md:text-5xl">{user.name ?? user.login}</h2><p className="font-mono text-muted text-base">@{user.login}</p></div>{user.bio && <p className="mt-3 text-muted leading-relaxed max-w-[65ch]">{user.bio}</p>}<div className="mt-6 grid grid-cols-1 sm:grid-cols-3 gap-6 sm:gap-x-8">{stats.map((stat) => <div key={stat.label} className="px-6 first:pl-0 sm:pl-6"><div className="font-mono text-xl text-ink">{stat.value}</div><div className="mt-1 text-muted text-xs">{stat.label}</div></div>)}</div><div className="mt-6"><Link href={user.html_url} target="_blank" rel="noopener noreferrer" className="text-accent hover:underline">{d.pages.openGithub}</Link></div></div></header><section className="mt-16 md:mt-20"><h2 className="font-mono text-lg text-ink">{d.pages.repositories}</h2><div className="mt-4"><RepoExplorer repos={repos} /></div></section></div>; }
